In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv("electric_vehicles_spec_2025.csv.csv")

In [7]:
df.head()

,brand,model,top_speed_kmh,battery_capacity_kWh,battery_type,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,...,towing_capacity_kg,cargo_volume_l,seats,drivetrain,segment,length_mm,width_mm,height_mm,car_body_type,source_url
0,Abarth,500e Convertible,155,37.8,Lithium-ion,192.0,235.0,156,225,7.0,...,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback,https://ev-database.org/car/1904/Abarth-500e-C...
1,Abarth,500e Hatchback,155,37.8,Lithium-ion,192.0,235.0,149,225,7.0,...,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback,https://ev-database.org/car/1903/Abarth-500e-H...
2,Abarth,600e Scorpionissima,200,50.8,Lithium-ion,102.0,345.0,158,280,5.9,...,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV,https://ev-database.org/car/3057/Abarth-600e-S...
3,Abarth,600e Turismo,200,50.8,Lithium-ion,102.0,345.0,158,280,6.2,...,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV,https://ev-database.org/car/3056/Abarth-600e-T...
4,Aiways,U5,150,60.0,Lithium-ion,NaN,310.0,156,315,7.5,...,NaN,496,5,FWD,JC - Medium,4680,1865,1700,SUV,https://ev-database.org/car/1678/Aiways-U5

In [8]:
df['segment'].value_counts()

segment
JC - Medium          91
JD - Large           58
F - Luxury           51
N - Passenger Van    47
JB - Compact         44
C - Medium           34
E - Executive        30
JF - Luxury          30
B - Compact          29
D - Large            28
JE - Executive       28
A - Mini              3
JA - Mini             2
G - Sports            2
I - Luxury            1
Name: count, dtype: int64

In [9]:
df=df.drop(["brand","model","battery_type","fast_charge_port","number_of_cells","seats","drivetrain","source_url"],axis=1)

In [10]:
df.head()

,top_speed_kmh,battery_capacity_kWh,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,fast_charging_power_kw_dc,towing_capacity_kg,cargo_volume_l,segment,length_mm,width_mm,height_mm,car_body_type
0,155,37.8,235.0,156,225,7.0,67.0,0.0,185,B - Compact,3673,1683,1518,Hatchback
1,155,37.8,235.0,149,225,7.0,67.0,0.0,185,B - Compact,3673,1683,1518,Hatchback
2,200,50.8,345.0,158,280,5.9,79.0,0.0,360,JB - Compact,4187,1779,1557,SUV
3,200,50.8,345.0,158,280,6.2,79.0,0.0,360,JB - Compact,4187,1779,1557,SUV
4,150,60.0,310.0,156,315,7.5,78.0,NaN,496,JC - Medium,4680,1865,1700,SUV

In [55]:
df['car_body_type'].unique()

array(['Hatchback', 'SUV', 'Station/Estate', 'Liftback Sedan', 'Sedan',
       'Small Passenger Van', 'Cabriolet', 'Coupe'], dtype=object)

In [11]:
df.shape

(478, 14)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   top_speed_kmh              478 non-null    int64
 1   battery_capacity_kWh       478 non-null    float64
 2   torque_nm                  471 non-null    float64
 3   efficiency_wh_per_km       478 non-null    int64
 4   range_km                   478 non-null    int64
 5   acceleration_0_100_s       478 non-null    float64
 6   fast_charging_power_kw_dc  477 non-null    float64
 7   towing_capacity_kg         452 non-null    float64
 8   cargo_volume_l             477 non-null    object
 9   segment                    478 non-null    object
 10  length_mm                  478 non-null    int64
 11  width_mm                   478 non-null    int64
 12  height_mm                  478 non-null    int64
 13  car_body_type              478 non-null    object
dtypes: float64(5), int64(6), object(3)
memory usage: 52.4+ KB

In [13]:
df['cargo_volume_l'].isnull().sum()

np.int64(1)

In [14]:
df.dropna(subset="cargo_volume_l",inplace=True)

In [15]:
df['cargo_volume_l'].isnull().sum()

np.int64(0)

In [16]:
df["cargo_volume_l"] = (
    df["cargo_volume_l"]
    .astype(str)
    .apply(lambda x: float(x.split()[0]) * 52 
           if "Banana" in x 
           else float(x))
)

In [17]:
df['cargo_volume_l'].unique()

array([ 185.,  360.,  496.,  472.,  400.,  326.,  502.,  520.,  535.,
        526.,  511.,  514.,  350.,  405.,  470.,  490.,  570.,  500.,
        525.,  440.,  345.,  308.,  552.,  235.,  385.,  540.,  793.,
        775., 1050.,  310.,  460.,  380.,  510.,  603.,  989.,  390.,
        620.,  467.,  361.,  572.,  536.,  519.,  523.,  672.,  228.,
        333.,  354.,  432.,  503.,  438.,  280.,  480.,  401.,  338.,
        466.,  505.,  355.,  550.,  839.,  435.,  475.,  309.,  210.,
        522.,  316.,  611.,  509.,  456.,  410.,  249.,  363.,  479.,
        453.,  448.,  151.,  270., 1612.,  340.,  495.,  430.,  645.,
        676.,  828.,  551., 1410., 1030.,  555., 1390.,  990.,  300.,
        200.,  579.,  265.,  386.,  450.,  468.,  415.,  819.,  352.,
        516.,  267.,  434.,  588.,  412.,  608.,  471.,  348.,  407.,
        484.,  446.,  366.,  367.,  420.,  950.,  545.,  585.,  313.,
        323.,  370.,  630.,  441.,  594.,  709.,  425.,  854.,  452.,
        376., 1340., 1121.,  543.,  549.,  532.,  605.,  404.,  318.,
        571.,  660.,  539.,  362.])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 477 entries, 0 to 477
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   top_speed_kmh              477 non-null    int64
 1   battery_capacity_kWh       477 non-null    float64
 2   torque_nm                  470 non-null    float64
 3   efficiency_wh_per_km       477 non-null    int64
 4   range_km                   477 non-null    int64
 5   acceleration_0_100_s       477 non-null    float64
 6   fast_charging_power_kw_dc  476 non-null    float64
 7   towing_capacity_kg         451 non-null    float64
 8   cargo_volume_l             477 non-null    float64
 9   segment                    477 non-null    object
 10  length_mm                  477 non-null    int64
 11  width_mm                   477 non-null    int64
 12  height_mm                  477 non-null    int64
 13  car_body_type              477 non-null    object
dtypes: float64(6), int64(6), object(2)
memory usage: 55.9+ KB

In [19]:
df.isnull().mean()*100

top_speed_kmh                0.000000
battery_capacity_kWh         0.000000
torque_nm                    1.467505
efficiency_wh_per_km         0.000000
range_km                     0.000000
acceleration_0_100_s         0.000000
fast_charging_power_kw_dc    0.209644
towing_capacity_kg           5.450734
cargo_volume_l               0.000000
segment                      0.000000
length_mm                    0.000000
width_mm                     0.000000
height_mm                    0.000000
car_body_type                0.000000
dtype: float64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('range_km',axis=1),
                                                   df['range_km'],
                                                   test_size=0.2,
                                                   random_state=42)

In [21]:
y_train.shape

(381,)

In [22]:
num_cols= X_train.drop(["segment","car_body_type"],axis=1).columns.tolist()
num_trans= Pipeline(steps=[
    ("impute",SimpleImputer(add_indicator=True)),
    ("scale",StandardScaler())
])

In [23]:
cat_cols= X_train[["segment","car_body_type"]].columns.tolist()
cat_trans= Pipeline(steps=[
    ("ohe",OneHotEncoder(handle_unknown="ignore"))
])

In [24]:
preprocessor = ColumnTransformer(transformers=[
    ("num",num_trans,num_cols),
    ("cat",cat_trans,cat_cols)
])

In [25]:
pipe = Pipeline(steps=[
    ("preprocess",preprocessor),
    ("model",RandomForestRegressor())
])

In [26]:
from sklearn import set_config
set_config(display="diagram")
pipe

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'height_mm']),
                                                 ('cat',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['segment',
                                                   'car_body_type'])])),
                ('model', RandomForestRegressor())])

In [27]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'height_mm']),
                                                 ('cat',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['segment',
                                                   'car_body_type'])])),
                ('model', RandomForestRegressor())])

In [28]:
ypred = pipe.predict(X_test)
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error, accuracy_score
r2_score(y_test,ypred), mean_absolute_error(y_test, ypred)

(0.9596488035792601, 14.015703125)

In [29]:
from sklearn.base import clone
pipe_knn = Pipeline(steps=[
    ("preprocess",clone(preprocessor)),
    ("model2",KNeighborsRegressor())
])

In [30]:
pipe_knn.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'height_mm']),
                                                 ('cat',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['segment',
                                                   'car_body_type'])])),
                ('model2', KNeighborsRegressor())])

In [31]:
ypred1 = pipe_knn.predict(X_test)
r2_score(y_test,ypred1), mean_absolute_error(y_test, ypred1)

(0.8451688882845989, 29.927083333333332)

In [32]:
pipe_svc = Pipeline(steps=[
    ("preprocess",clone(preprocessor)),
    ("model2",SVR())
])

In [33]:
pipe_svc.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'height_mm']),
                                                 ('cat',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['segment',
                                                   'car_body_type'])])),
                ('model2', SVR())])

In [34]:
ypred2 = pipe_svc.predict(X_test)
r2_score(y_test,ypred2), mean_absolute_error(y_test, ypred2)

(0.3333913496850497, 67.87799075387416)

In [35]:
pipe_dt = Pipeline(steps=[
    ("preprocess",preprocessor),
    ("model2",DecisionTreeRegressor())
])

In [36]:
pipe_dt.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'height_mm']),
                                                 ('cat',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['segment',
                                                   'car_body_type'])])),
                ('model2', DecisionTreeRegressor())])

In [37]:
ypred3 = pipe_dt.predict(X_test)
r2_score(y_test,ypred3), mean_absolute_error(y_test, ypred3)

(0.9271798656908518, 19.479166666666668)

In [38]:
pipe_logr = Pipeline(steps=[
    ("preprocess",clone(preprocessor)),
    ("model2",LinearRegression())
])

In [39]:
pipe_logr.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'height_mm']),
                                                 ('cat',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['segment',
                                                   'car_body_type'])])),
                ('model2', LinearRegression())])

In [40]:
ypred4 = pipe_logr.predict(X_test)
r2_score(y_test,ypred4), mean_absolute_error(y_test, ypred4)

(0.9554866480289318, 16.60657023252662)

In [41]:
pipe_xgb = Pipeline(steps=[
    ("preprocess",clone(preprocessor)),
    ("model2",XGBRegressor())
])

In [42]:
pipe_xgb.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(add_indicator=True)),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['top_speed_kmh',
                                                   'battery_capacity_kWh',
                                                   'torque_nm',
                                                   'efficiency_wh_per_km',
                                                   'acceleration_0_100_s',
                                                   'fast_charging_power_kw_dc',
                                                   'towing_capacity_kg',
                                                   'cargo_volume_l',
                                                   'length_mm', 'width_mm',
                                                   'hei...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [43]:
ypred4 = pipe_xgb.predict(X_test)
r2_score(y_test,ypred4), mean_absolute_error(y_test, ypred4)

(0.9452714323997498, 14.176948547363281)

In [44]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

209    265
205    265
430    285
311    485
22     395
      ...
106    230
271    360
349    525
436    525
102    390
Name: range_km, Length: 381, dtype: int64